name: Push Container to Okteto

#TODO: Replace by:
  #on:
  #push:
    #branches: [ main ]
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Version
        uses: actions/setup-node@v2
      
      - name: Setup dependencies
        run: |
          sudo npm install -g npm
          npm -v
          node -v
          sudo npm install --global yarn
          yarn --version
          yarn --frozen-lockfile
      - name: Run lint
        run: yarn lint:ci --fix
      #- name: Run tests
        #run: yarn test
  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - uses: actions/checkout@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ubademyg12/payments-service

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: "Activate personal namespace"
      uses: okteto/namespace@master
      with:
        name: distance71

    - name: "Create deployment"
      uses: okteto/apply@master
      with:
        manifest: k8s.yml
